### ISSUE TITLE
The homepage shows an error after a few seconds

### ISSUE THREAD

**Issue by etabakov** [EddyVerbruggen/nativescript-app-sync-web#2] opened 2019-07-15 13:43 UTC
After loading the homepage, everything is ok for a while and then the error from the screenshot is shown. 
![Screenshot 2019-07-15 at 16 43 04](https://user-images.githubusercontent.com/2611328/61220761-aa083480-a71f-11e9-816c-fd55f0448def.png)

**Comment by EddyVerbruggen** [comment] 2019-07-15 15:00
What the..? Is that related to a particular browser perhaps? Or some browser plugin maybe?

**Comment by etabakov** [comment] 2019-07-15 15:54
Might be .. I'm testing with latest Chrome (Version 75.0.3770.100 (Official Build) (64-bit)) on macOS. It doesn't happen on Safari nor when opening with Chrome on my phone.

**Comment by EddyVerbruggen** [comment] 2019-07-16 07:09
@etabakov I just updated Chrome on macOS to that version as well and still doesn't happen to me. It would be very helpful to know if this happens all the time, and how exactly. Can you please log out from that website and clear your browser cache and see if and when it happens?

FYI a similar issue was reported before and I thought I fixed it, although it was similarly hard to reproduce), so that's why I'm partly suspecting browser cache.

**Comment by etabakov** [comment] 2019-07-16 07:34
OK, that's getting even weirder. The problem is steadily reproducible even in incognito tab. I disabled all the plugins and it still reproducible. What I think you will enjoy is that when I open the developer tools investigate - the problem is different 😈 It fails loading "https://appsync-server.nativescript.org/WEB_USAGE.md" and shows a similar red error:
```
TypeError: Failed to fetch
TypeError: Failed to fetch
```

The only additional error I can see in the console is:

```
warning.js:33 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ></div></div></div><div style="position:
 (server) ></div></div></div></div>
```

**Comment by EddyVerbruggen** [comment] 2019-07-16 08:03
I see those errors in the console as well, but even when opening https://appsync.nativescript.org in incognito the homepage loads and stays as-is. Mind blowing stuff 🤯

**Comment by lee-devopa** [comment] 2019-08-01 14:10
Few things that might be useful - Seems to be caused by 
```
case 'Object':
      var keys = (0, _keys2.default)(data);
      if (!isWideLayout) return keys.length ? '{…}' : '{}';

      str = keys.slice(0, 3).map(function (key) {
        return key + ': ' + getShortTypeString(data[key], isDiff);
      }).concat(keys.length > 3 ? ['…'] : []).join(', ');

      return '{ ' + str + ' }';
```

Not sure where this is from but as a side note of that, it works if you make your window smaller, refresh the page and then resize to normal

**Comment by EddyVerbruggen** [comment] 2019-08-01 14:13
> Not sure where this is from but as a side note of that, it works if you make your window smaller, refresh the page and then resize to normal

🤯

**Comment by EddyVerbruggen** [comment] 2019-08-01 14:18
@lee-devopa Those lines are from the `redux-devtools-inspector` package. Sounds like something that should not be part of a live app anyway.. but perhaps I can see if they updated that package..

**Comment by Naxos84** [comment] 2019-08-01 14:38
is this related to:
https://github.com/EddyVerbruggen/nativescript-app-sync-server/issues/3
???

**Comment by EddyVerbruggen** [comment] 2019-08-01 14:39
@Naxos84 Yes, same issue.

**Comment by EddyVerbruggen** [comment] 2019-08-02 21:40
@etabakov @lee-devopa @Naxos84 @dudipsh @afaridanquah Please recheck the website, because @edusperoni has attempted to create a fix.. we'd really like to know if the problem is solved for you guys as well. Make sure to do a hard refresh/cache clean to be sure you get the latest bits.

**Comment by dudipsh** [comment] 2019-08-03 11:45
@EddyVerbruggen 
I don't get the error anymore!

**Comment by EddyVerbruggen** [comment] 2019-08-03 15:17
That's good to hear! Closing for now 😄

**Closed as completed by EddyVerbruggen** 2019-08-03 15:17 UTC

**Comment by EddyVerbruggen** [comment] 2019-08-04 15:10
@dudipsh Do you have this issue as well? https://github.com/EddyVerbruggen/nativescript-app-sync-server/issues/2#issuecomment-517989240

**Comment by dudipsh** [comment] 2019-08-04 15:22
@EddyVerbruggen 
No, but for some reason, i don't get an updates...

Edit*
it works!

**Comment by Naxos84** [comment] 2019-08-05 06:03
I can confirm that there are no errors anymore. (For both Chrome & Firefox on Win10)

Thx.

**Comment by etabakov** [comment] 2019-08-05 07:21
No errors on my side as well. Good job, @EddyVerbruggen and @edusperoni!
